name:                codacy-hadolint
version:             0.1.0.0
github:              "codacy/codacy-hadolint"
license:             MIT
author:              "João Lopes"
maintainer:          "lopes@codacy.com"
copyright:           "2018 Codacy"

extra-source-files:
- ../README.md

description:         Please see the README on GitHub at <https://github.com/codacy/codacy-hadolint#readme>

dependencies:
- base >= 4.8 && < 5

library:
  source-dirs: src
  dependencies:
    - &Prettyprint prettyprinter >= 1.7.0
    - &ShellCheck ShellCheck >=0.8.0
    - &bytestring bytestring >=0.10
    - &split split >=0.2
    - containers
    - filemanip
    - Cabal
    - HsYAML
    - aeson
    - bytestring
    - cryptonite
    - deepseq >= 1.4.4 && < 1.5
    - directory >= 1.3.0
    - email-validate
    - filepath
    - foldl
    - gitrev >=1.3.1
    - ilist
    - mtl
    - network-uri
    - parallel
    - parsec >= 3.1.14
    - semver
    - spdx
    - time
    - timerep >= 2.0
    - void
    - text

executables:
  codacy-hadolint:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - codacy-hadolint
    when:
    - condition: '!(os(osx))'
      ld-options:
        - -static
        - -pthread
