name:                codacy-hadolint
version:             0.1.0.0
github:              "codacy/codacy-hadolint"
license:             MIT
author:              "Codacy"
maintainer:          "code@codacy.com"
copyright:           "2018 Codacy"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/codacy/codacy-hadolint#readme>

dependencies:
- base >= 4.8 && < 5

library:
  source-dirs: src
  dependencies:
    - &bytestring bytestring >=0.10
    - text
    - aeson
    - bytestring
    - hadolint == 2.10.0
    - containers
    - directory
    - filemanip

executables:
  codacy-hadolint:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - codacy-hadolint
    when:
    - condition: '!(os(osx))'
      ld-options:
        - -static
        - -pthread
